inherit_gem:
  rubocop-fjord:
    - "config/rubocop.yml"
    - "config/rails.yml"

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/PerceivedComplexity:
  Max: 10

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 160

AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - '**/templates/**/*'
    - '**/vendor/**/*'
    - app/views/**/*
    - config/**/*
    - config.ru
    - node_modules/**/*
    - db/migrate/*
    - db/schema.rb
    - storage/**/*
    - tmp/**/*
    - bin/**/*
